### PR TITLE
Add Exploring Localness Blogpost

### PR DESCRIPTION
**Pull request by itisacloud**
fixed exploring loclaness blogpost

### CODE REVIEW

**Comment by Hagellach37** [comment]
Hey @itisacloud ,
I have a few comments for minor improvements:
* can you add `matplotlib`, `ipyleaflet`, `pyproj` to the requirements.txt
* fix typo `Liiterature` at the bottom
* handle `MatplotlibDeprecationWarning`: The rowNum attribute was deprecated in Matplotlib 3.2 and will be removed two minor releases later. Use ax.get_subplotspec().rowspan.start instead.
    * either ignore or use the proposed implementation
* can you add an estimate how long some cells will take and add this as a comment to the cell? e.g. `.plotTagcompletness` takes some more time right?

Other than that things worked fine for me. Great work! :+1:

**Comment by tyrasd** [comment]
This is indeed a nice notebook @itisacloud, very well made and structured!

Other than what @Hagellach37 already mentioned, I believe there is a glitch in the plot for the buildings graph in section "level 4":

image

--

Except for this, I believe this _analysis_ is not a perfect fit for this _examples_ repository: The examples here should be mostly easy-to-follow, technically focused showcases of how the API can be used, while your analysis is already quite a bit more elaborate and really deserves to live in its own repository, I think. See also #18 

I have created a new repository for it on our gitlab: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/ohsome-api-analysis-examples/exploring-localness-blogpost/ (@itisacloud should already have full access to it).

**Comment by tyrasd** [comment]
PS: in the finished notebook (e.g. as displayed on [nbviewer](https://nbviewer.jupyter.org/urls/gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/ohsome-api-analysis-examples/exploring-localness-blogpost/-/raw/master/Exploring%20Localness_Blogpost.ipynb)) I don't find the mentioned _Spatial Distribution map_. It also doesn't appear when running the notebook manually. Is that a bug?

**Comment by tyrasd** [comment]
PSS: I created two issues for the mentioned points:

* https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/ohsome-api-analysis-examples/exploring-localness-blogpost/-/issues/1
* https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/ohsome-api-analysis-examples/exploring-localness-blogpost/-/issues/2

**Pull request closed without merging**
